### ISSUE TITLE
Issue when rendering feedback

### ISSUE THREAD

**Issue by dailez** [oat-sa/qti-sdk#8]
There is a "bug" or better "not covered case" in the rendering routine in the qtism-sdk.

The problem occurs when the outcomeDeclaration of the feedback has cardinality=multiple (i.e. feedback_adaptive.xml).

The affected file is qtism/qtism/src/qtism/common/collections/Container.php -> public function equals($obj).

In the feedback example above the $obj type is "string" and the workaround is to add an elseif at the line 150:
        elseif (gettype($obj) === 'string') {
            foreach (array_keys($this->getDataPlaceHolder()) as $key) {
                if ($obj === $this[$key]->getValue()) {
                    return true;
                }
            }
            return false;
        }

Would you please so kind to check it and let me know if I misunderstood something. 

Kindest regards

**Comment by bugalot** [comment]
Thanks @dailez for your report. Actually, your identification of the issue seems good. However, the fix should not go in the equals() method of the Container class but rather in the rendering engine itself which should also try to check whether or not the Container->contains() the identifier.

I will make a patch to this. Thanks a lot for your feedback. It is much appreciated!

**Comment by bugalot** [comment]
The following commit on the master branch should make it 13ed421768dbd8f23e040280927941d83fde7c8d

If you need the 0.9.x branch to be updated quick, just let me know.

**Comment by dailez** [comment]
Thank you very much! It is now working like a charm.
